version: "3.1"
services:
  postgres:
    container_name: django_postgres_development
    image: postgres:alpine
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: ${DJANGO_DATABASE_PSWD}
      POSTGRES_USER: ${DJANGO_DATABASE_USER}
      POSTGRES_DB: ${DJANGO_DATABASE_NAME}
      PGPORT: ${DJANGO_DATABASE_PORT}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DJANGO_DATABASE_PORT}:${DJANGO_DATABASE_PORT}
